apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xwqp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0025-tenant/cin4s-839-0025-app/devfile-sample-xwqp@sha256:afa66a1e804106ddac8da29508e2014edd408ce35b74b03ef96cad1e1a5920dd
        name: my-nodejs
        resources: {}
status: {}
